/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.Paiscontroller;
import Model.Entity.Continentes;
import Model.Entity.Pais;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author supap
 */
public class Ventana4 extends javax.swing.JInternalFrame {

    Paiscontroller PsC = new Paiscontroller();
    Pais ps = new Pais();
    DefaultTableModel modelo;

    public Ventana4() {
        initComponents();
        ListarContinentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablapaises = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        BTNGUARDAR = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtBucar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpaisid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setNormalBounds(new java.awt.Rectangle(10, 0, 104, 0));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablapaises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CODIGO", "DESPRICION", "CONTINENTE_ID"
            }
        ));
        tablapaises.setShowGrid(false);
        tablapaises.setSurrendersFocusOnKeystroke(true);
        tablapaises.setUpdateSelectionOnSort(false);
        tablapaises.setVerifyInputWhenFocusTarget(false);
        tablapaises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablapaisesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablapaises);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 239, 1033, 188));

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 206, -1, -1));

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(921, 206, -1, -1));

        BTNGUARDAR.setText("Agregar");
        BTNGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGUARDARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNGUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 206, -1, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));
        getContentPane().add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 96, 30, -1));

        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 101, -1, -1));

        jLabel2.setText("Codigo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 133, -1, -1));

        jLabel3.setText("DESCRIP:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 162, -1, -1));

        TxtBucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBucarActionPerformed(evt);
            }
        });
        TxtBucar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBucarKeyTyped(evt);
            }
        });
        getContentPane().add(TxtBucar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 300, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("Paises Europa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setText("Paisid:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 101, -1, -1));
        getContentPane().add(txtpaisid, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 96, 59, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/asdasdasdasdasd.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-440, 0, 1600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGUARDARActionPerformed

        String codigo_postal;
        String descripcion;

        if (!"".equals(txtid.getText()) || !"".equals(txtCodigo.getText()) || !"".equals(txtdescripcion.getText()) || !"".equals(txtpaisid.getText())) {
            codigo_postal = txtCodigo.getText();
            descripcion = txtdescripcion.getText();

            PsC.GuardarRegistro(WIDTH, codigo_postal, descripcion);
            LimpiarTable();
            Limpiar();
            ListarContinentes();

            JOptionPane.showMessageDialog(null, "Cliente Registrado");

            BTNGUARDAR.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Los campos estan vacios");

        }


    }//GEN-LAST:event_BTNGUARDARActionPerformed

    private void tablapaisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapaisesMouseClicked
        BTNGUARDAR.setEnabled(false);
        int fila = tablapaises.rowAtPoint(evt.getPoint());
        txtid.setText(tablapaises.getValueAt(fila, 0).toString());
        txtCodigo.setText(tablapaises.getValueAt(fila, 1).toString());
        txtdescripcion.setText(tablapaises.getValueAt(fila, 2).toString());
        txtpaisid.setText(tablapaises.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_tablapaisesMouseClicked

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        int id;
        String codigo_postal;
        String descripcion;
        String contiente_id;

        if ("".equals(txtid.getText())) {
            JOptionPane.showMessageDialog(null, "Seleecione una fila");
        } else {
            if (!"".equals(txtCodigo.getText()) || !"".equals(txtdescripcion.getText()) || !"".equals(txtpaisid.getText())) {
                ps.setCodigo_postal(txtCodigo.getText());

                id = Integer.parseInt(txtid.getText());
                codigo_postal = txtCodigo.getText();
                descripcion = txtdescripcion.getText();
                contiente_id = txtpaisid.getText();

                System.out.println("datos del view  " + contiente_id);

                // contiente_id = Integer.parseInt(txtpaisid.getText());
                PsC.Modificar(id, codigo_postal, descripcion, contiente_id);
                JOptionPane.showMessageDialog(null, " Modificado");
                LimpiarTable();
                Limpiar();
                ListarContinentes();
                btnmodificar.setEnabled(false);
                BTNGUARDAR.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, " No se pudeo Hcaer el Cambio");

            }
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int Id;

        if (!txtid.getText().isEmpty()) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar?" ,"title", JOptionPane.PLAIN_MESSAGE);
            if (pregunta == 0) {
                Id = Integer.parseInt(txtid.getText());
                PsC.EliminarRegistroF(Id);
                LimpiarTable();
                Limpiar();
                ListarContinentes();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila.");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtBucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBucarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBucarActionPerformed
TableRowSorter trs;

    private void TxtBucarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBucarKeyTyped
           trs = new TableRowSorter(modelo);
        tablapaises.setRowSorter(trs);

        TxtBucar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter(TxtBucar.getText(), 2));
            }
        });

    }//GEN-LAST:event_TxtBucarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNGUARDAR;
    private javax.swing.JTextField TxtBucar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablapaises;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtpaisid;
    // End of variables declaration//GEN-END:variables

    public void ListarContinentes() {
        List<Pais> ListarPaises = ps.ListarPaises();
        modelo = (DefaultTableModel) tablapaises.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < ListarPaises.size(); i++) {
            ob[0] = ListarPaises.get(i).getId();
            ob[1] = ListarPaises.get(i).getCodigo_postal();
            ob[2] = ListarPaises.get(i).getDescripcion();
            ob[3] = ListarPaises.get(i).getIdContinente();
            modelo.addRow(ob);
        }
        tablapaises.setModel(modelo);
    }

    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    public void Limpiar() {
        txtid.setText("");
        txtCodigo.setText("");
        txtdescripcion.setText("");
        txtpaisid.setText("");

    }

}
