/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * ventana3.java
 *
 * Created on 24-abr-2013, 13:39:55
 */
package View;

import Controller.ContinentesController;
import Model.Entity.Continentes;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuario
 */
public class ventana3 extends javax.swing.JInternalFrame {

    Continentes cont = new Continentes();
    ContinentesController contCroller = new ContinentesController();
    DefaultTableModel modelo;

    public ventana3() {
        initComponents();
        ListarContinentes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnmodifica = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BtnEliminaFisico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContinetes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtBucar = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Continentes");

        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnmodifica.setText("Modificar");
        btnmodifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificaActionPerformed(evt);
            }
        });

        jButton3.setText("Elimar L");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        BtnEliminaFisico.setText("Eliminar");
        BtnEliminaFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminaFisicoActionPerformed(evt);
            }
        });

        tablaContinetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CODIGO", "DESCRIPCION"
            }
        ));
        tablaContinetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaContinetesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaContinetes);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("Continente Europa");

        jLabel2.setText("ID:");

        jLabel3.setText("Contn:");

        jLabel4.setText("Nombre:");

        TxtBucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBucarActionPerformed(evt);
            }
        });
        TxtBucar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBucarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 815, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtBucar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnmodifica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnEliminaFisico)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodifica)
                    .addComponent(jButton3)
                    .addComponent(btnGuardar)
                    .addComponent(BtnEliminaFisico)
                    .addComponent(TxtBucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    String codigo_postal;
    String descripcion;

    if (!"".equals(txtid.getText()) || !"".equals(txtCodigo.getText()) || !"".equals(txtdescripcion.getText())) {
        codigo_postal = txtCodigo.getText();
        descripcion = txtdescripcion.getText();

        contCroller.GuardarRegistro(codigo_postal, descripcion);
        LimpiarTable();
        Limpiar();
        ListarContinentes();

        JOptionPane.showMessageDialog(null, "Cliente Registrado");

        btnGuardar.setEnabled(true);
    } else {
        JOptionPane.showMessageDialog(null, "Los campos estan vacios");

    }


}//GEN-LAST:event_btnGuardarActionPerformed

    private void tablaContinetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaContinetesMouseClicked
       btnGuardar.setEnabled(false);
        int fila = tablaContinetes.rowAtPoint(evt.getPoint());
        txtid.setText(tablaContinetes.getValueAt(fila, 0).toString());
        txtCodigo.setText(tablaContinetes.getValueAt(fila, 1).toString());
        txtdescripcion.setText(tablaContinetes.getValueAt(fila, 2).toString()); 

    }//GEN-LAST:event_tablaContinetesMouseClicked

    private void btnmodificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificaActionPerformed
        int id;
        String codigo_postal;
        String descripcion;

        if ("".equals(txtid.getText())) {
            JOptionPane.showMessageDialog(null, "Seleecione una fila");
        } else {
            if (!"".equals(txtCodigo.getText()) || !"".equals(txtdescripcion.getText())) {
                cont.setCodigo_postal(txtCodigo.getText());

                id = Integer.parseInt(txtid.getText());
                codigo_postal = txtCodigo.getText();
                descripcion = txtdescripcion.getText();
                contCroller.Modificar(id, codigo_postal, descripcion);

                JOptionPane.showMessageDialog(null, " Modificado");
                LimpiarTable();
                Limpiar();
                ListarContinentes();
                btnmodifica.setEnabled(false);
                btnGuardar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, " No se pudeo Hcaer el Cambio");

            }
        }
    }//GEN-LAST:event_btnmodificaActionPerformed

    private void BtnEliminaFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminaFisicoActionPerformed

        int Id;

        if (!txtid.getText().isEmpty()) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar?");
            if (pregunta == 0) {
                Id = Integer.parseInt(txtid.getText());
                contCroller.EliminarRegistroF(Id);
                LimpiarTable();
                Limpiar();
                ListarContinentes();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila.");
        }


    }//GEN-LAST:event_BtnEliminaFisicoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  



    }//GEN-LAST:event_jButton3ActionPerformed

    private void TxtBucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBucarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBucarActionPerformed
TableRowSorter trs;
    private void TxtBucarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBucarKeyTyped
         trs = new TableRowSorter(modelo);
        tablaContinetes.setRowSorter(trs);

        TxtBucar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter(TxtBucar.getText(), 2));
            }
        });


       
    }//GEN-LAST:event_TxtBucarKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminaFisico;
    private javax.swing.JTextField TxtBucar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnmodifica;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tablaContinetes;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

    public void ListarContinentes() {
        List<Continentes> listarContinentes = cont.ListarContinentes();
        modelo = (DefaultTableModel) tablaContinetes.getModel();
        Object[] ob = new Object[3];
        for (int i = 0; i < listarContinentes.size(); i++) {
            ob[0] = listarContinentes.get(i).getId();
            ob[1] = listarContinentes.get(i).getCodigo_postal();
            ob[2] = listarContinentes.get(i).getDescripcion();
            modelo.addRow(ob);
        }
        tablaContinetes.setModel(modelo);
    }

    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    public void Limpiar() {
        txtid.setText("");
        txtCodigo.setText("");
        txtdescripcion.setText("");

    }

}
